### ISSUE TITLE
nil

### ISSUE THREAD

**Issue by wendychaung** [Web3-Camp/test-issue#91]
{
  "Name": "nil", 
  "Slug": "nil", 
  "Github": "web3-camp/test-issue",
  "Tagline": "Decentralized Curated NFT Marketplace",
  "Mission": "il is a c ommunity-curated marketplace looking to harmonize the relationship between the creator economy participants.\n\nWe are a cooperative of hackers & painters looking to collectively establish the decentralized foundations on which the creator economy will thrive.",
  "Values": "Put the power of NFTs in the hand of the people",
  "TokenSymbol": "$ETH",
  "TokenContractAddress": "0x33d3fF69E5967b3E6Cdc95206F1AbdF0709406",
  "Logo": "https://daocentral.com/_next/image?url=http%3A%2F%2Fres.cloudinary.com%2Fdaojones%2Fimage%2Fupload%2Fv1643641724%2Fqabekepttq1jfrqjs067.jpg&w=3840&q=75",
  "CoverPhoto": "https://daocentral.com/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdaojones%2Fimage%2Fupload%2Fv1638064462%2Flr335nwc9gaetl2ir43v.png&w=3840&q=75",
  "Twitter": "daotest2Twitter",
  "Discord": "daotest2Discord",
  "Mirror": "daotest2Mirror",
  "Website": "daotest2.Website.com",
  "Email": "fdasf@gmail.com" 
}

**Comment by xrdavies** [comment]
Your DAO is already in the list. Please check the list and resubmit.
